project_id = "svkmahihzzfwlbeebfwj"

[functions.aggregate-template-sum]
verify_jwt = false

[functions.fetch-acs-snapshot]
verify_jwt = false

[functions.purge-acs-storage]
verify_jwt = false

[functions.purge-backfill-data]
verify_jwt = false

[functions.sv-rewards-summary]
verify_jwt = false

[functions.upload-acs-data]
verify_jwt = false
